
networks:
  tamreen:
    driver: bridge

volumes:
  tamreen:
  tamreen-logs:

services:
  tamreen:
    image: cybrarist/tamreen:latest
#    build:
#      context: .
    ports:
      - 8080:80
    networks:
      - tamreen
    volumes:
      - ./database/database.sqlite:/app/database/database.sqlite
      - ./.env:/app/.env
      - ./logs:/logs
    environment:
      DB_CONNECTION: sqlite
      APP_TIMEZONE: UTC
      APP_URL: "http://localhost:8080"
      ASSET_URL: "http://localhost:8080"
      ALLOW_REGISTER: true
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_USERNAME: "email@gmail.com"
      MAIL_PASSWORD: "app password"
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: "email@gmail.com"

